// This file is auto-generated by vite-plugin-route-builder
// Do not edit manually
/* eslint-disable */
// @ts-nocheck

import type { RouteObject } from "react-router"

// Imports for page components
const lazy0 = () => import("./pages/layout")
const lazy1 = () => import("./pages/about")
const lazy2 = () => import("./pages/index")

// Generated route configuration
export const routes: RouteObject[] = [
  {
    "path": "",
    "lazy": lazy0,
    "children": [
      {
        "path": "about",
        "lazy": lazy1
      },
      {
        "path": "",
        "lazy": lazy2
      }
    ]
  }
]

export default routes
